### ISSUE TITLE
Вот что пишет. Шабанг не правильный. Надо изменить на #!

### ISSUE THREAD

**Issue by vsysoev** [vsysoev/sarfti-fall-2013#2]
Vladimirs-MacBook-Air:task_3 vsysoev$ python ./hello.py 
  File "./hello.py", line 1
    !#/usr/bin/python
    ^
SyntaxError: invalid syntax

**Comment by AKorezin** [comment]
still exists?

**Comment by vsysoev** [comment]
Yes, If fixed, should be closed by Ann.
