### ISSUE TITLE
twitter.exe reported file not found

### ISSUE THREAD

**Issue by vsysoev** [vsysoev/sarfti-fall-2013#8]

**Comment by AKorezin** [comment]
Программу надо запускать с аргументом местонахождения файла массивов.

**Comment by vsysoev** [comment]
Почему я должен это знать? Должен быть help, если нужный параметр не указан.

**Comment by AKorezin** [comment]
problem remains, don't close

**Comment by AKorezin** [comment]
#9

**Comment by AKorezin** [comment]
:fuuuuuuuu:. Нельзя закрывать чужие issue если вы не принимаете в них явного участия со стороны руководителя репозитория в который или из которого происходит pull request. 
Причиной закрытия может считаться:
- Автор правки отозвал свою правку.
- Владелец репозитория не хочет чтобы правка была принята (wontfix).
- Данная проблема уже была (duplicate).
- Проблемы не существует вообще (invalid).

Во всех остальных случаях проблема должна оставаться незакрытой (ну в идеале оно так и должно быть).
Обсуждать в комментах проблему можно.

**Comment by vsysoev** [comment]
Артем, 
Задача №8 требует, чтобы на входе был массив из высот стен, а на выходе только объем воды. Должно быть только одно число. Я не понял, что выводит Ваш файл twitter. Более того, не надо называть Ваши исполняемые файлы, громкими именами. Антивирусы могут ополчиться.

**Comment by AKorezin** [comment]
Вводить руками много массивов это очень сложно. Программа выводит количество воды, проверьте данные в файле из которого читает программа. Каждая новая строка это новый массив стен. Мне кажется это должно быть логически ясно...

**Comment by AKorezin** [comment]
А что насчет #10?

**Comment by AKorezin** [comment]
Для справки. В гисте у автора новости не было вообще ввода данных извне.

**Comment by AKorezin** [comment]
Done. Closed.
